### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wolfv** [bkircher/libsolv-rs#1]
Hi, 

Are you planning to add a license to your code? That would facilitate reuse!

**Comment by bkircher** [comment]
Sure. However this is far from usable

**Comment by wolfv** [comment]
yep, no problem. So far i've just copied your headers into my repo. Once I add more features, I'll contribute as much back as possible :)

https://github.com/wolfv/crusty

**Comment by wolfv** [comment]
Btw the motivation of this package is to make conda faster. If you're interested, here is the prototype code that I am trying to port to Rust / libsolv-rs: https://gist.github.com/wolfv/f06a8a73c83920387d4dd6e67961c7f2

**Comment by bkircher** [comment]
Yeah, I should devote more time to this here.

> motivation of this package is to make conda faster.

Cool. As somebody who uses conda every day, this is very much appreciated. My idea was to use it in Fedora.

Anyway, do you have a license in mind that would suit your needs?

**Comment by wolfv** [comment]
I think BSD3 is a good, business friendly license. Or just use the same license as libsolv? 

I also saw that some libsolv folks are working on Rust bindings here: https://github.com/ignatenkobrain/libsolv-rs/

However, I am not completely understanding how that is used, and there was a weird merge-unmerge happening :) Just in case you're not aware.

**Comment by bkircher** [comment]
[libsolv](https://github.com/openSUSE/libsolv) itself is BSD. Seems that a dual-license MIT/Apache 2 is [common or desired](https://rust-lang-nursery.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) in Rust ecosystem but BSD is also fine. I guess, we just make it BSD then.

> I also saw that some libsolv folks are working on Rust bindings here: https://github.com/ignatenkobrain/libsolv-rs/

Yes, I met Igor at a conference and we wanted to add a proper binding for libsolv. Looks like this was a first attempt.

**Comment by wolfv** [comment]
sounds good!

**Comment by bkircher** [comment]
Done
